spring:
  thymeleaf:
    enabled: true
  mail:
    host: localhost
    port: 10025
  #    host: smtp.gmail.com
  #    port: 587
  #    username: username
  #    password: password
  #    properties:
  #      mail.smtp.auth: true
  #      mail.smtp.starttls.enable: true
  #      mail.smtp.ssl.trust: smtp.gmail.com
  messages:
    basename: messages # default
#  artemis:
#    broker-url: tcp://localhost:61616 # default
#  jms:
#    listener:
#      concurrency: 10
#    pub-sub-domain: true # topic

#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: ${random.uuid}
#      properties:
#        spring.json.trusted.packages: pl.training.chat
languages: pl
main-room: /main-room
private-rooms-prefix: /private-rooms/
messages-topic: messages
