version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      MONGO_INITDB_ROOT_DATABASE: "payments"
  mail:
    image: djfarrelly/maildev
    command: home/node/bin/maildev --web 8082 --smtp 10025
    ports:
      - "8082:8082"
      - "10025:10025"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    image: redis
    ports:
      - "6379:6379"
  hazelcast:
    image: hazelcast/hazelcast
    ports:
      - "5701:5701"
  hazelcast-manager:
    image: hazelcast/management-center
    ports:
      - "8083:8080"

