version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      MONGO_INITDB_ROOT_DATABASE: "payments"
  mail:
    image: djfarrelly/maildev
    command: home/node/bin/maildev --web 8082 --smtp 10025
    ports:
      - "8082:8082"
      - "10025:10025"
