spring:
  datasource:
    url: jdbc:h2:file:./data/payments-development.db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    open-in-view: false
  messages:
    basename: exceptions
