spring:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
  messages:
    basename: exceptions
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/payments.db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/payments?authSource=admin&authMechanism=SCRAM-SHA-256
      auto-index-creation: true
  cloud:
    openfeign:
      client:
        config:
          dateTimeApi:
            logger-level: headers
logging:
  level:
    org.springframework.data.mongodb.repository.query: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    pl.training.payments.adapters.output.time.remote: DEBUG
loggerOrder: 10000
dateTimeApi: http://worldtimeapi.org/api/timezone/Europe/Warsaw
processedPaymentsApi: http://localhost:8081/payments/processed
tokenApi: 123
