server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/reactive-payments?authSource=admin&authMechanism=SCRAM-SHA-256
      auto-index-creation: true
logging:
  level:
    org.springframework.data.mongodb.repository.query: DEBUG
